### ISSUE TITLE
cleanup deletes all keys

### ISSUE THREAD

**Issue by jonseymour** [JohannesBuchner/Python-LRU-cache#1]
I think the referenced for loop, will result in all keys being deleted, not just the oldest ones.

https://github.com/JohannesBuchner/SimpleLRUCache/blob/7b22ca2d26a386b0116c4e8d44c8bff6babd2b19/simplelrucache/__init__.py#L70

**Comment by JohannesBuchner** [comment]
The inner loop picks the oldest key (because OrderedDict), deletes it and exits the loop.

The outer loop repeats until the number of elements is below or at max_size.

It's a bit subtle.

**Comment by jonseymour** [comment]
I see what you mean. Sorry about that!
